print("Shela May Revilla Rogelio")
print("Hupi, Santa Cruz, Marinduque")
print("October 4, 2001")
print("Marinduque State College")
print("Bachelor of Science Information Technology")
print("2nd Year College")
print("Section 2-A")
